### ISSUE TITLE
Android implementation native crashes

### ISSUE THREAD

**Issue by artrobert** [artoolkitx/artoolkitx#120] opened 2020-08-25 09:51 UTC
Hi, while developing and android App using the library I get some crashes most when I close the camera preview. The code is more or less similar with the one from the AR2DTracking_Project example.

Here are some of the stacktrace:

/app E/libc++abi: terminating with uncaught exception of type cv::Exception: OpenCV(3.4.0-dev) /opencv/modules/core/src/matrix.cpp:464: error: (-215) 0 <= roi.x && 0 <= roi.width && roi.x + roi.width <= m.cols && 0 <= roi.y && 0 <= roi.height && roi.y + roi.height <= m.rows in function Mat 
A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 31267 (ImageReaderThread)

/app E/cv::error(): OpenCV(3.4.0-dev) Error: Assertion failed (scn + 1 == m.cols) in perspectiveTransform, file opencv/modules/core/src/matmul.cpp line 2268 
/app E/libc++abi: terminating with uncaught exception of type cv::Exception: OpenCV(3.4.0-dev) /opencv/modules/core/src/matmul.cpp:2268: error: (-215) scn + 1 == m.cols in function perspectiveTransform 08-12 
app A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 28705 (ImageReaderThread)

Is strange that this happens when the camera preview is closed and I want to know if:
1) this is really a crash from OpenCV and is nothing that can be done about it from your side or my side
2) is a crash from how the library communicates with OpenCV and will be fixed in a future lib version
3) is something I am not doing right while using the library

Thanks in advance for the answer.

**Comment by Yaugan** [comment] 2020-11-05 07:09
I am also having the same error, as I build my app from Unity. When I test it, it crashes again and again and I don't understand why this is happening

**Comment by philip-lamb** [comment] 2023-06-07 02:36
Closing this as unable to reproduce with new native camera module on Android.

**Closed by philip-lamb** 2023-06-07 02:36 UTC
Labels: invalid
