### ISSUE TITLE
Windows 10: Error: a required OpenGL function counld not be bound.

### ISSUE THREAD

**Issue by 640kb** [artoolkitx/artoolkitx#66] opened 2018-11-19 12:08 UTC
I am trying to use the artoolkitx under Windows 10 now, but have problems with tools like check_id. The initializing fails, because some OpenGL functions couldn't be found. The precompiled binaries also fail with the same following messages:

>[debug] Resized to 1280x720.
>[info] Setting video configuration '-format=yuvs'.
>[info] Opening artoolkitX video using configuration '-format=yuvs'.
>[info] Using supplied video config "-format=yuvs".
>[info] Using supplied video config "-format=yuvs".
>[info] Requesting images in yuvs/YUY2 format.
>[info] Video 640x480 (AR_PIXEL_FORMAT_yuvs), rowBytes=1280.
>[info] Opened artoolkitX video 640x480@2Bpp (AR_PIXEL_FORMAT_yuvs).
>[warning] Using default camera parameters for 640x480 image size, 45 degrees vertical field-of-view.
>[debug] Video capture started.
>[debug] arVideoLuma will NOT use Intel SIMD acceleration.
>[debug] ARVideoView::initWithVideoSource.
>[debug] arglSetupForCurrentContext: api = ARG_API_GL3.
>[error] Error: a required OpenGL function counld not be bound.
>[error] Error initializing display of video frames from source.
>[error] Error: unable to init video view.
>[debug] ARVideoSource::close(): called.
>[debug] ARVideoSource::close(): stopping video.

The problem lies in arg_gl3.c in the function arglSetupForCurrentContextGL3, where ARGL_GET_PROC_ADDRESS fails. "glTexParameteri" is the first Opengl function of many where the binding fails.

ARGL_GET_PROC_ADDRESS("glTexParameterliv") returns NULL.
The call off GetLastError() returns "ERROR_PROC_NOT_FOUND"

Any Ideas how to solve this problem?

I already update my drivers. Here some informations about the hardware and software:

Windows 10 Enterprise, Version 1709
Intel I7-6700 CPU with an Intel HD 530 GPU (driver version 25.20.100.6373)
and a Nvidia Quadro P2000 (driver version 411.81)

**Comment by philip-lamb** [comment] 2018-11-20 11:57
I'll take a look at it. I haven't checked what OpenGL stack is used on the Azure Devops build, but check_id works with OpenGL 1.x rather than 3.x+, so there's definitely a mismatch if libARg is using OpenGL 3.x.

**Comment by Rikdeleeuw** [comment] 2019-03-28 09:12
Duplicate of #74?

**Comment by philip-lamb** [comment] 2019-08-29 22:53
Fixed in #98

**Closed by philip-lamb** 2019-08-29 22:53 UTC
