### ISSUE TITLE
AR2d Tracking sample doesn't detect the pinball.jpg

### ISSUE THREAD

**Issue by BingBingAR** [artoolkitx/artoolkitx#16] opened 2018-05-16 13:10 UTC
Hi
I've download artoolkitx1.0.1 and built the AR2d Tracking sample.
But I could not see that the sample app detects the marker.
How can I see if the app is correct?

**Comment by Neuroforge** [comment] 2018-05-17 03:04
Hello,

1) Are you using the pinball.jpg marker?
2) what resolution is your webcam?

Regards,

Daniel

**Comment by BingBingAR** [comment] 2018-05-17 03:13
Hello. Thanks your respond.
1. I used below pinball.jpg image as a marker.

2. My webcaom resolution is 640x480.
![pinball](https://user-images.githubusercontent.com/23514600/40154886-c2e5418e-59cb-11e8-8765-3bbf50eca911.jpg)

**Comment by BingBingAR** [comment] 2018-05-22 07:39
any news about my issue?
Can I use any 2d images as a marker, not only square image?

**Comment by ThorstenBux** [comment] 2018-05-22 08:19
Can you please list some steps to reproduce

1. Where did you download from or did you clone the repo
2. When you downloaded did you use the precompiled app or did you compile yourself
3. How did you compile?
4. What platform did you compile for
5. How did you deploy and run?

**Comment by BingBingAR** [comment] 2018-05-22 14:45
Hello. thanks for your kind reply.
1. I did download from this repository.
https://github.com/artoolkitx/artoolkitx/releases/download/1.0.1/artoolkitX.for.Windows.v1.0.1.zip
2. I used the precompiled app in artoolkitX.for.Windows.v1.0.1\a\SDK\bin\artoolkitx_2d_tracking_example.exe.
3. I didn't yet compile it.
4. My platform is Win10.
5. I only run the artoolkitx_2d_tracking_example.exe with double click on that directory.
I connected webcam to my pc and scan the pinball.jpg. but I can't see any cube.
Is there any mistake?
Thanks.

**Comment by ThorstenBux** [comment] 2018-05-25 06:25
Yes, there seem to be some issues with that. I'm still not entirely sure but it looks like it. We are a bit occupied with other stuff but keep this open.

**Comment by norips** [comment] 2018-05-31 11:39
Hi, I am having the same problem on Windows 10.
I have also tested it on linux by compiling it from this repo, same problem appear. But on android the example works even from the source.
Squared marker are working but not the 2d tracking.

@ThorstenBux Did you experience low fps (~5fps@720p or ~10fps@480p) on Android too ?

**Comment by XrizZ** [comment] 2018-06-13 13:47
I can confirm that this error exists, same on my machine. I tried resolutions from 640x480 all the way up to 1920x1080 - same results. Marker does not get detected.

**Comment by ThorstenBux** [comment] 2018-07-15 18:20
Have looked into this again. It is working on macOS but not on Windows. @Neuroforge any suggestions?

**Comment by Neuroforge** [comment] 2018-07-16 20:46
@BingBingAR @norips @XrizZ 

If you guys can open the artoolkitx.sln after running build.sh windows.

Inside of the OCVT project (Opencv Tracker) find OCVConfig.cpp.

Here you can change the presets used by the OpenCV Tracker.

```
#include "OCVConfig.h"

int minRequiredDetectedFeatures = 50;
int markerTemplateWidth = 15;
int maxLevel = 3;
const cv::Size subPixWinSize(10,10), winSize(31,31);
cv::TermCriteria termcrit(cv::TermCriteria::COUNT|cv::TermCriteria::EPS,20,0.03);
const int MAX_COUNT = 300;
int maxNumberOfToTrack = 1;
int searchRadius = 15;
int match_method = cv::TM_SQDIFF_NORMED;
int featureDetectPyramidLevel = 2;
int defaultDetectorType = 0;
const double nn_match_ratio = 0.8f; // Nearest-neighbour matching ratio
const double ransac_thresh = 2.5f; // RANSAC inlier threshold
cv::RNG rng( 0xFFFFFFFF );
int harrisBorder = 10;
```

Change **defaultDetectorType** to the value of 1. This will switch to ORB feature tracking which seems to work on Windows. Not sure why AKAZE is having an issue and i am still investigating.

**Comment by SCornu** [comment] 2019-04-01 10:07
Hi, I am having the same problem on a project with Android, i am using the app that comes with the zip file.

If someone can help me with this problem I would appreciate it

**Comment by kalwalt** [comment] 2019-08-17 19:20
@ThorstenBux i tested the 2d tracking with a linux built but the app can not detect the pinball image.
@Neuroforge I tried changing the  defaultDetectorType ( i tested all available...) but without luck. Maybe we need to change the setup? Under Macos it seems to works, right?

**Comment by ThorstenBux** [comment] 2019-08-18 08:47
I have had it working on macOS but never tried Linux setup

**Comment by kalwalt** [comment] 2019-08-18 12:06
i tested the `AKAZE_match.ccp` sample from OpenCV 3.4.0 the same version i used to build with ARToolKitX and it works perfectly for me, Maybe the problem is not OpenCV itself but maybe data not arrive correctly to OCVT module?

**Comment by philip-lamb** [comment] 2023-03-30 00:45
Fixed in https://github.com/artoolkitx/artoolkitx/pull/143

**Closed by philip-lamb** 2023-03-30 00:45 UTC
Labels: bug
