### ISSUE TITLE
Slow Processing Speed

### ISSUE THREAD

**Issue by XrizZ** [artoolkitx/artoolkitx#15] opened 2018-05-04 13:20 UTC
Does anyone have any suggestions on how to improve the processing speed for the square tracking? I get around 30fps if the input is 640x480, 10fps@720p and just 5fps@1080p. No single CPU core is maxing out. Whats the bottleneck?

I also tried to move the processing off to a different thread, keeping the render thread clean. However, this didn't improve the tracking speed either. Of course it improved the rendering speed, but then the 3D rendering was offset from the camera input as the marker moved. So I reverted to doing everything in the render thread, like in the official example.

Debug and Release mode have the same framerate.. any clue?

**Comment by philip-lamb** [comment] 2018-05-04 23:40
What platform and what are the CPU specs?

**Comment by XrizZ** [comment] 2018-05-07 09:51
The Platform is Windows 10, 64bit running on an Intel i7-8700K (6 cores).

**Comment by XrizZ** [comment] 2018-05-17 10:52
I was able to test it on a number of other machines now, also running Windows 7 and Windows 10, with about the same processing rate. There seems to be bottleneck by design - artoolkitx is not using all the resources it could. Maybe I will test what happens if I give OpenCV a few more parallelization features.

**Comment by philip-lamb** [comment] 2018-06-05 22:59
The square detector is single-threaded by design, but that is truely bad performance. I guess next step would be to profile it and see what's taking all the time.

**Comment by philip-lamb** [comment] 2018-10-08 00:06
To clarify, is this in the SDL-based examples? It could be just SDL not behaving. If no feedback on this issue, I will close it in a few days.

**Comment by XrizZ** [comment] 2018-10-08 15:17
Hi Philip, that was my first thought as well. But even when I completely take out SDL and use a fast window handler with bare OpenGL its still just as slow.

**Comment by philip-lamb** [comment] 2020-04-14 21:59
Closing some really old issues, but with a note that if you're using adaptive thresholding, the algorithm is unaccelerated on Windows, Linux and Android (on macOS and iOS it uses Accelerate.framework's optimised filter operation), so that would be one thing to check.

**Closed by philip-lamb** 2020-04-14 21:59 UTC
